[workspace]
resolver = "3"
members = [
    "src/rust"
]

[workspace.package]
description = "这是一个用 Rust 实现的 scrapyd 高性能 SDK，既支持同步操作也支持协程模式，并通过 pyo3 封装成易用的 Python 库。"
version = "0.1.0"
edition = "2021"
publish = false

[workspace.dependencies]
pyo3 = { version = "0.24.1", features = ["extension-module", "abi3-py38", "chrono", "chrono-tz"] }
