[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "scrust"
description = "这是一个用 Rust 实现的 scrapyd 高性能 SDK，既支持同步操作也支持协程模式，并通过 pyo3 封装成易用的 Python 库。"
readme = "README.md"
authors = [
    { name = "屿你有关", email = "978814197@qq.com" },
    { name = "Weilet", email = "Weilet_Sun@outlook.com" },
]
license = { file = "LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/OxideZoo/scrust"
Repository = "https://github.com/OxideZoo/scrust.git"


[tool.maturin]
python-source = "src"
python-packages = ["scrust"]
manifest-path = "src/rust/Cargo.toml"
module-name = "scrust.backends.bindings._rust"
features = ["pyo3/extension-module", "pyo3/abi3-py38"]
abi3-py-version = "3.8"